import { GamerInterface } from "common/interfaces";

export const gamers: GamerInterface[] = [
  {
    id: 1,
    isActive: true,
    isKilled: false,
    isBlocked: false,
    incomingAbilities: [],
    role: {
      id: "doctor",
      name: "Лікарка",
      type: "city",
      isActiveNight: true,
      isDisabled: false,
      priority: 3,
      desctiption:
        "Грає за мирних, Просинається у ночі та лікує одного гравця, не можно лікувати себе чи іншого гравця 2 рази підряд",
      abilities: ["healing"],
    },
  },
  {
    id: 2,
    isActive: true,
    isKilled: false,
    isBlocked: false,
    incomingAbilities: [],
    role: {
      id: "godfather",
      name: "Хрещений батько",
      type: "mafia",
      isActiveNight: true,
      isDisabled: false,
      priority: 4,
      desctiption:
        "Лідер мафії, Просинаеться у ночі. Вирішує разом зі своєю командою в кого мафія буде стріляти у ночі",
      abilities: ["killing"],
    },
  },
  {
    id: 3,
    isActive: true,
    isKilled: false,
    isBlocked: false,
    incomingAbilities: [],
    role: {
      id: "chameleon",
      name: "Хамелеон",
      type: "mafia",
      isActiveNight: false,
      isDisabled: false,
      priority: 20,
      desctiption:
        "Грає за мафію при перевірці завжди буде як звичайний мешканець міста",
      abilities: [],
    },
  },
  {
    id: 4,
    isActive: true,
    isKilled: false,
    isBlocked: false,
    incomingAbilities: [],
    role: {
      id: "mafiosi",
      name: "Мафіозі",
      type: "mafia",
      isActiveNight: true,
      isDisabled: false,
      priority: 5,
      desctiption:
        "Грає за мафію якщо вбивають хрещеного батька займає його місце",
      abilities: ["killing"],
    },
  },
  {
    id: 5,
    isActive: true,
    isKilled: false,
    isBlocked: false,
    incomingAbilities: [],
    role: {
      id: "sheriff",
      name: "Шериф",
      type: "city",
      isActiveNight: true,
      isDisabled: false,
      priority: 7,
      desctiption:
        "Грає за мирних, Шериф просинається у ночі та має змогу перевіряти або стріляти",
      abilities: ["checkPersonTeam", "killing"],
    },
  },
  {
    id: 6,
    isActive: true,
    isKilled: false,
    isBlocked: false,
    incomingAbilities: [],
    role: {
      id: "maniac",
      name: "Маніяк",
      type: "self",
      isActiveNight: true,
      isDisabled: false,
      priority: 8,
      desctiption:
        "Просинаеться у ночі, Грає самостійно від мафії та мирних стріляє у одного з участників",
      abilities: ["killing"],
    },
  },
  {
    id: 7,
    isActive: true,
    isKilled: false,
    isBlocked: false,
    incomingAbilities: [],
    role: {
      id: "detective",
      name: "Детектив",
      type: "city",
      isActiveNight: true,
      isDisabled: false,
      priority: 9,
      desctiption:
        "Грає за мирних, просинається у ночі, вибирає двух гравців, та може дізнатися грають вони за одну команду або ні",
      abilities: ["comparePersonsTeam"],
    },
  },
  {
    id: 8,
    isActive: true,
    isKilled: false,
    isBlocked: false,
    incomingAbilities: [],
    role: {
      id: "beauty",
      name: "Шанувальниця",
      type: "city",
      isActiveNight: true,
      isDisabled: false,
      priority: 10,
      desctiption:
        "Грає за мирних, просинається у ночі та обирає одного гравця, якщо цей гравець шериф то дізнається його роль",
      abilities: ["checkSheriffRole"],
    },
  },
  {
    id: 9,
    isActive: true,
    isKilled: false,
    isBlocked: false,
    incomingAbilities: [],
    role: {
      id: "peaceful",
      name: "Мирний мешканець",
      type: "city",
      isActiveNight: false,
      isDisabled: false,
      priority: 20,
      desctiption: "Грає за мирних",
      abilities: [],
    },
  },

  {
    id: 10,
    isActive: true,
    isKilled: false,
    isBlocked: false,
    incomingAbilities: [],
    role: {
      id: "peaceful",
      name: "Мирний мешканець",
      type: "city",
      isActiveNight: false,
      isDisabled: false,
      priority: 20,
      desctiption: "Грає за мирних",
      abilities: [],
    },
  },
  {
    id: 11,
    isActive: true,
    isKilled: false,
    isBlocked: false,
    incomingAbilities: [],
    role: {
      id: "peaceful",
      name: "Мирний мешканець",
      type: "city",
      isActiveNight: false,
      isDisabled: false,
      priority: 20,
      desctiption: "Грає за мирних",
      abilities: [],
    },
  },
];
