import { PresetTypesInterface } from "common/interfaces";

export const presetTypes: PresetTypesInterface[] = [
  {
    id: 1,
    type: 6,
    presets: [
      {
        id: 1,
        name: "Легка гра",
        roles: [
          "doctor",
          "godfather",
          "mafiosi",
          "sheriff",
          "peaceful",
          "peaceful",
        ],
      },
      {
        id: 2,
        name: "Сильне місто",
        roles: [
          "doctor",
          "godfather",
          "mafiosi",
          "sheriff",
          "admirer",
          "peaceful",
        ],
      },
      {
        id: 3,
        name: "М'ясо",
        roles: [
          "doctor",
          "godfather",
          "sheriff",
          "maniac",
          "peaceful",
          "peaceful",
        ],
      },
    ],
  },
  {
    id: 1,
    type: 7,
    presets: [
      {
        id: 1,
        name: "Легка гра",
        roles: [
          "godfather",
          "mafiosi",
          "sheriff",
          "peaceful",
          "peaceful",
          "peaceful",
          "peaceful",
        ],
      },
      {
        id: 2,
        name: "Сильне місто",
        roles: [
          "doctor",
          "godfather",
          "sheriff",
          "admirer",
          "peaceful",
          "peaceful",
          "peaceful",
        ],
      },
      {
        id: 3,
        name: "М'ясо",
        roles: [
          "sheriff",
          "godfather",
          "mafiosi",
          "maniac",
          "peaceful",
          "peaceful",
          "peaceful",
        ],
      },
    ],
  },
  {
    id: 1,
    type: 8,
    presets: [
      {
        id: 1,
        name: "Легка гра",
        roles: [
          "doctor",
          "godfather",
          "mafiosi",
          "sheriff",
          "peaceful",
          "peaceful",
          "peaceful",
          "peaceful",
        ],
      },
      {
        id: 2,
        name: "Сильне місто",
        roles: [
          "doctor",
          "godfather",
          "mafiosi",
          "sheriff",
          "admirer",
          "peaceful",
          "peaceful",
          "peaceful",
        ],
      },
      {
        id: 3,
        name: "М'ясо",
        roles: [
          "doctor",
          "godfather",
          "mafiosi",
          "sheriff",
          "maniac",
          "peaceful",
          "peaceful",
          "peaceful",
        ],
      },
      {
        id: 4,
        name: "Активні ролі",
        roles: [
          "doctor",
          "godfather",
          "mafiosi",
          "chameleon",
          "sheriff",
          "detective",
          "peaceful",
          "peaceful",
        ],
      },
    ],
  },
  {
    id: 1,
    type: 9,
    presets: [
      {
        id: 1,
        name: "Легка гра",
        roles: [
          "doctor",
          "godfather",
          "mafiosi",
          "sheriff",
          "peaceful",
          "peaceful",
          "peaceful",
          "peaceful",
          "peaceful",
        ],
      },
      {
        id: 2,
        name: "Сильне місто",
        roles: [
          "doctor",
          "godfather",
          "mafiosi",
          "sheriff",
          "admirer",
          "peaceful",
          "peaceful",
          "peaceful",
          "peaceful",
        ],
      },
      {
        id: 3,
        name: "М'ясо",
        roles: [
          "doctor",
          "godfather",
          "mafiosi",
          "sheriff",
          "maniac",
          "peaceful",
          "peaceful",
          "peaceful",
          "peaceful",
        ],
      },
      {
        id: 4,
        name: "Сильна мафія м'ясо",
        roles: [
          "doctor",
          "godfather",
          "mafiosi",
          "mafiosi",
          "sheriff",
          "maniac",
          "peaceful",
          "peaceful",
          "peaceful",
        ],
      },
      {
        id: 5,
        name: "Сильна мафія",
        roles: [
          "doctor",
          "godfather",
          "mafiosi",
          "mafiosi",
          "sheriff",
          "peaceful",
          "peaceful",
          "peaceful",
          "peaceful",
        ],
      },
      {
        id: 6,
        name: "Активні ролі",
        roles: [
          "doctor",
          "godfather",
          "mafiosi",
          "chameleon",
          "sheriff",
          "detective",
          "peaceful",
          "peaceful",
          "peaceful",
        ],
      },
    ],
  },
  {
    id: 1,
    type: 10,
    presets: [
      {
        id: 1,
        name: "Легка гра",
        roles: [
          "doctor",
          "godfather",
          "mafiosi",
          "mafiosi",
          "sheriff",
          "peaceful",
          "peaceful",
          "peaceful",
          "peaceful",
          "peaceful",
        ],
      },
      {
        id: 2,
        name: "Сильне місто",
        roles: [
          "doctor",
          "godfather",
          "mafiosi",
          "mafiosi",
          "sheriff",
          "admirer",
          "peaceful",
          "peaceful",
          "peaceful",
          "peaceful",
        ],
      },
      {
        id: 3,
        name: "М'ясо",
        roles: [
          "doctor",
          "godfather",
          "mafiosi",
          "mafiosi",
          "sheriff",
          "maniac",
          "admirer",
          "peaceful",
          "peaceful",
          "peaceful",
        ],
      },
      {
        id: 4,
        name: "Сильна мафія м'ясо",
        roles: [
          "doctor",
          "godfather",
          "mafiosi",
          "chameleon",
          "sheriff",
          "maniac",
          "admirer",
          "peaceful",
          "peaceful",
          "peaceful",
        ],
      },
      {
        id: 5,
        name: "Сильна мафія",
        roles: [
          "doctor",
          "godfather",
          "mafiosi",
          "mafiosi",
          "sheriff",
          "peaceful",
          "peaceful",
          "peaceful",
          "peaceful",
          "peaceful",
        ],
      },
    ],
  },
  {
    id: 1,
    type: 11,
    presets: [
      {
        id: 1,
        name: "Легка гра",
        roles: [
          "doctor",
          "godfather",
          "mafiosi",
          "mafiosi",
          "sheriff",
          "peaceful",
          "peaceful",
          "peaceful",
          "peaceful",
          "peaceful",
          "peaceful",
        ],
      },
      {
        id: 2,
        name: "Сильне місто",
        roles: [
          "doctor",
          "godfather",
          "mafiosi",
          "mafiosi",
          "sheriff",
          "admirer",
          "peaceful",
          "peaceful",
          "peaceful",
          "peaceful",
          "peaceful",
        ],
      },
      {
        id: 3,
        name: "М'ясо",
        roles: [
          "doctor",
          "godfather",
          "mafiosi",
          "mafiosi",
          "sheriff",
          "maniac",
          "admirer",
          "peaceful",
          "peaceful",
          "peaceful",
          "peaceful",
        ],
      },
      {
        id: 4,
        name: "Сильна мафія м'ясо",
        roles: [
          "doctor",
          "godfather",
          "mafiosi",
          "mafiosi",
          "sheriff",
          "maniac",
          "peaceful",
          "peaceful",
          "peaceful",
          "peaceful",
          "peaceful",
        ],
      },
      {
        id: 5,
        name: "Сильна мафія",
        roles: [
          "doctor",
          "godfather",
          "mafiosi",
          "mafiosi",
          "sheriff",
          "peaceful",
          "peaceful",
          "peaceful",
          "peaceful",
          "peaceful",
          "peaceful",
        ],
      },
    ],
  },
  {
    id: 1,
    type: 12,
    presets: [
      {
        id: 1,
        name: "Легка гра",
        roles: [
          "doctor",
          "godfather",
          "mafiosi",
          "mafiosi",
          "sheriff",
          "peaceful",
          "peaceful",
          "peaceful",
          "peaceful",
          "peaceful",
          "peaceful",
          "peaceful",
        ],
      },
      {
        id: 2,
        name: "Сильне місто",
        roles: [
          "doctor",
          "godfather",
          "mafiosi",
          "mafiosi",
          "sheriff",
          "admirer",
          "peaceful",
          "peaceful",
          "peaceful",
          "peaceful",
          "peaceful",
          "peaceful",
        ],
      },
      {
        id: 3,
        name: "М'ясо",
        roles: [
          "doctor",
          "godfather",
          "mafiosi",
          "mafiosi",
          "sheriff",
          "maniac",
          "admirer",
          "peaceful",
          "peaceful",
          "peaceful",
          "peaceful",
          "peaceful",
        ],
      },
      {
        id: 4,
        name: "Сильна мафія м'ясо",
        roles: [
          "doctor",
          "godfather",
          "mafiosi",
          "mafiosi",
          "sheriff",
          "maniac",
          "peaceful",
          "peaceful",
          "peaceful",
          "peaceful",
          "peaceful",
          "peaceful",
        ],
      },
      {
        id: 5,
        name: "Сильна мафія",
        roles: [
          "doctor",
          "godfather",
          "mafiosi",
          "mafiosi",
          "sheriff",
          "peaceful",
          "peaceful",
          "peaceful",
          "peaceful",
          "peaceful",
          "peaceful",
          "peaceful",
        ],
      },
    ],
  },
];
